FROM registry.gitlab.com/dedyms/sid-slim:latest AS fetcher
ARG RELEASE
ENV ARCH
ADD https://github.com/AnalogJ/scrutiny/releases/download/$RELEASE/scrutiny-collector-metrics-linux-$ARCH /
RUN chmod +x scrutiny-collector-metrics-linux-amd64

FROM registry.gitlab.com/dedyms/sid-slim:latest
ARG RELEASE
ARG ARCH
#ENV SCRUTINY_VERSION=$RELEASE
RUN apt update && apt install --no-install-recommends -y smartmontools cron && apt clean && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /scrutiny/collector
COPY --from=fetcher /scrutiny-collector-metrics-linux-${ARCH} /scrutiny/collector/scrutiny-collector-metrics-linux-$ARCH
COPY scrutiny.cron /etc/cron.d/scrutiny
CMD cron -f 
